namespace ADCloudReplacer.Translation;

/// <summary>
/// A class that has the keys of the translation string.
/// This code was automatically generated by T4.
/// </summary>
public static class KeyStrings
{

    /// <summary>
    /// Source: replace and enables the cloud used in After Dark(before weather update) 
    /// </summary>
    public const string MOD_DESC = "MOD_DESC";

    /// <summary>
    /// Source:  (Vanilla)
    /// </summary>
    public const string VANILLA_LABEL = "VANILLA_LABEL";

    /// <summary>
    /// Source: Select
    /// </summary>
    public const string TAB_NAME_SELECT = "TAB_NAME_SELECT";

    /// <summary>
    /// Source: Properties
    /// </summary>
    public const string TAB_NAME_PROPERTIES = "TAB_NAME_PROPERTIES";

    /// <summary>
    /// Source: Support
    /// </summary>
    public const string TAB_NAME_SUPPORT = "TAB_NAME_SUPPORT";

    /// <summary>
    /// Source: Enable AD Cloud
    /// </summary>
    public const string ENABLE_AD_CLOUD = "ENABLE_AD_CLOUD";

    /// <summary>
    /// Source: Select Cloud
    /// </summary>
    public const string SELECT_CLOUD = "SELECT_CLOUD";

    /// <summary>
    /// Source: Refresh
    /// </summary>
    public const string TIP_REFRESH_BTN = "TIP_REFRESH_BTN";

    /// <summary>
    /// Source: Open the local folder
    /// </summary>
    public const string TIP_OPENLOCALFOLDER_BTN = "TIP_OPENLOCALFOLDER_BTN";

    /// <summary>
    /// Source: Download more clouds from Steam Workshop
    /// </summary>
    public const string TIP_DMFWORKSHOP_BTN = "TIP_DMFWORKSHOP_BTN";

    /// <summary>
    /// Source: Apply
    /// </summary>
    public const string APPLY_BTN = "APPLY_BTN";

    /// <summary>
    /// Source: Vanilla clouds are dependent on map environment and can only be seen in-game.
    /// </summary>
    public const string TIP_VANILLA_PREVIEW = "TIP_VANILLA_PREVIEW";

    /// <summary>
    /// Source: Size
    /// </summary>
    public const string CLOUD_SIZE_LABEL = "CLOUD_SIZE_LABEL";

    /// <summary>
    /// Source: Control Mode
    /// </summary>
    public const string CONTROL_MODE = "CONTROL_MODE";

    /// <summary>
    /// Source: Control
    /// </summary>
    public const string GROUP_CONTROL = "GROUP_CONTROL";

    /// <summary>
    /// Source: Vanilla
    /// </summary>
    public const string MODE_VANILLA = "MODE_VANILLA";

    /// <summary>
    /// Source: Custom
    /// </summary>
    public const string MODE_CUSTOM = "MODE_CUSTOM";

    /// <summary>
    /// Source: Load the vanilla values. changed values will not be saved.
    /// </summary>
    public const string TIP_VANILLA_MODE = "TIP_VANILLA_MODE";

    /// <summary>
    /// Source: Changed value will be saved to config.
    /// </summary>
    public const string TIP_CUSTOM_MODE = "TIP_CUSTOM_MODE";

    /// <summary>
    /// Source: Reset to Vanilla
    /// </summary>
    public const string RESET_TO_VANILLA_BTN = "RESET_TO_VANILLA_BTN";

    /// <summary>
    /// Source: Load the vanilla values by the current environment
    /// </summary>
    public const string TIP_RESET_TO_VANILLA_BTN = "TIP_RESET_TO_VANILLA_BTN";

    /// <summary>
    /// Source: Alpha Saturation
    /// </summary>
    public const string ALPHA_SATURATION = "ALPHA_SATURATION";

    /// <summary>
    /// Source: Attenuation
    /// </summary>
    public const string ATTENUATION = "ATTENUATION";

    /// <summary>
    /// Source: Step Size
    /// </summary>
    public const string STEP_SIZE = "STEP_SIZE";

    /// <summary>
    /// Source: Rotate Speed
    /// </summary>
    public const string ROTATE_SPPED = "ROTATE_SPPED";

    /// <summary>
    /// Source: Sky Color Multiplier
    /// </summary>
    public const string SKY_COLOR_MULTIPLIER = "SKY_COLOR_MULTIPLIER";

    /// <summary>
    /// Source: Sun Color Multiplier
    /// </summary>
    public const string SUN_COLOR_MULTIPLIER = "SUN_COLOR_MULTIPLIER";

    /// <summary>
    /// Source: In Vanilla mode, setting control available in game
    /// </summary>
    public const string TIP_DISABLED_CONTROL_PANEL = "TIP_DISABLED_CONTROL_PANEL";

    /// <summary>
    /// Source: Steam Workshop Page
    /// </summary>
    public const string STEAM_WORKSHOP_PAGE_BTN = "STEAM_WORKSHOP_PAGE_BTN";

    /// <summary>
    /// Source: Github Repository
    /// </summary>
    public const string GITHUB_REPOSITORY_BTN = "GITHUB_REPOSITORY_BTN";

    /// <summary>
    /// Source: Select Language
    /// </summary>
    public const string SELECT_LANGUAGE = "SELECT_LANGUAGE";

    /// <summary>
    /// Source: Use game language
    /// </summary>
    public const string USE_GAME_LANGUAGE = "USE_GAME_LANGUAGE";

    /// <summary>
    /// Source: Localization
    /// </summary>
    public const string GROUP_LOCALIZATION = "GROUP_LOCALIZATION";

    /// <summary>
    /// Source: Interested in translation? Visit the mod's Crowdin project.
    /// </summary>
    public const string CROWDIN_LINK_DESC = "CROWDIN_LINK_DESC";

    /// <summary>
    /// Source: In-Game UI
    /// </summary>
    public const string GROUP_INGAMEUI = "GROUP_INGAMEUI";

    /// <summary>
    /// Source: Show Mod Button
    /// </summary>
    public const string SHOW_MOD_BUTTON = "SHOW_MOD_BUTTON";

    /// <summary>
    /// Source: Mod Button Position
    /// </summary>
    public const string MOD_BUTTON_POSITION = "MOD_BUTTON_POSITION";

    /// <summary>
    /// Source: Panel Position
    /// </summary>
    public const string PANEL_POSITION = "PANEL_POSITION";

    /// <summary>
    /// Source: Reset
    /// </summary>
    public const string RESET_BTN = "RESET_BTN";

    /// <summary>
    /// Source: Not set
    /// </summary>
    public const string NOT_SET = "NOT_SET";

    /// <summary>
    /// Source: Please enter the valid values before applying
    /// </summary>
    public const string TIP_DISABLED_APPLYBTN = "TIP_DISABLED_APPLYBTN";

    /// <summary>
    /// Source: Discord Server
    /// </summary>
    public const string DISCORD_BTN = "DISCORD_BTN";
}
