namespace nnCitiesShared.Translation;

/// <summary>
/// A class that has the keys of the translation string.
/// This code was automatically generated by T4.
/// </summary>
public static partial class KeyStrings
{

    /// <summary>
    /// Source: Replace and enables the cloud used in After Dark(before weather update). Version {Version} <br/>
    /// Context: 
    /// </summary>
    public const string MOD_DESC = "MOD_DESC";

    /// <summary>
    /// Source: Select <br/>
    /// Context: 
    /// </summary>
    public const string TAB_NAME_SELECT = "TAB_NAME_SELECT";

    /// <summary>
    /// Source: Properties <br/>
    /// Context: 
    /// </summary>
    public const string TAB_NAME_PROPERTIES = "TAB_NAME_PROPERTIES";

    /// <summary>
    /// Source: Support <br/>
    /// Context: 
    /// </summary>
    public const string TAB_NAME_SUPPORT = "TAB_NAME_SUPPORT";

    /// <summary>
    /// Source: Enable AD Cloud <br/>
    /// Context: 
    /// </summary>
    public const string ENABLE_AD_CLOUD = "ENABLE_AD_CLOUD";

    /// <summary>
    /// Source: Select Cloud <br/>
    /// Context: 
    /// </summary>
    public const string SELECT_CLOUD = "SELECT_CLOUD";

    /// <summary>
    /// Source: Refresh <br/>
    /// Context: 
    /// </summary>
    public const string TIP_REFRESH_BTN = "TIP_REFRESH_BTN";

    /// <summary>
    /// Source: Open the local folder <br/>
    /// Context: 
    /// </summary>
    public const string TIP_OPENLOCALFOLDER_BTN = "TIP_OPENLOCALFOLDER_BTN";

    /// <summary>
    /// Source: Download more clouds from Steam Workshop <br/>
    /// Context: 
    /// </summary>
    public const string TIP_DMFWORKSHOP_BTN = "TIP_DMFWORKSHOP_BTN";

    /// <summary>
    /// Source: Vanilla clouds depend on the map environment, so you can only preview it in-game. <br/>
    /// Context: 
    /// </summary>
    public const string TIP_VANILLA_PREVIEW = "TIP_VANILLA_PREVIEW";

    /// <summary>
    /// Source: Size <br/>
    /// Context: 
    /// </summary>
    public const string CLOUD_SIZE_LABEL = "CLOUD_SIZE_LABEL";

    /// <summary>
    /// Source: Control Mode <br/>
    /// Context: 
    /// </summary>
    public const string CONTROL_MODE = "CONTROL_MODE";

    /// <summary>
    /// Source: Control <br/>
    /// Context: 
    /// </summary>
    public const string GROUP_CONTROL = "GROUP_CONTROL";

    /// <summary>
    /// Source: Load the vanilla values. changed values will not be saved. <br/>
    /// Context: 
    /// </summary>
    public const string TIP_VANILLA_MODE = "TIP_VANILLA_MODE";

    /// <summary>
    /// Source: Changed value will be saved to config. <br/>
    /// Context: 
    /// </summary>
    public const string TIP_CUSTOM_MODE = "TIP_CUSTOM_MODE";

    /// <summary>
    /// Source: Reset to Vanilla <br/>
    /// Context: 
    /// </summary>
    public const string RESET_TO_VANILLA_BTN = "RESET_TO_VANILLA_BTN";

    /// <summary>
    /// Source: Load the vanilla values by the current environment <br/>
    /// Context: 
    /// </summary>
    public const string TIP_RESET_TO_VANILLA_BTN = "TIP_RESET_TO_VANILLA_BTN";

    /// <summary>
    /// Source: Alpha Saturation <br/>
    /// Context: 
    /// </summary>
    public const string ALPHA_SATURATION = "ALPHA_SATURATION";

    /// <summary>
    /// Source: Attenuation <br/>
    /// Context: 
    /// </summary>
    public const string ATTENUATION = "ATTENUATION";

    /// <summary>
    /// Source: Step Size <br/>
    /// Context: 
    /// </summary>
    public const string STEP_SIZE = "STEP_SIZE";

    /// <summary>
    /// Source: Rotate Speed <br/>
    /// Context: 
    /// </summary>
    public const string ROTATE_SPPED = "ROTATE_SPPED";

    /// <summary>
    /// Source: Sky Color Multiplier <br/>
    /// Context: 
    /// </summary>
    public const string SKY_COLOR_MULTIPLIER = "SKY_COLOR_MULTIPLIER";

    /// <summary>
    /// Source: Sun Color Multiplier <br/>
    /// Context: 
    /// </summary>
    public const string SUN_COLOR_MULTIPLIER = "SUN_COLOR_MULTIPLIER";

    /// <summary>
    /// Source: In vanilla mode, the setting control is only available in-game <br/>
    /// Context: 
    /// </summary>
    public const string TIP_DISABLED_CONTROL_PANEL = "TIP_DISABLED_CONTROL_PANEL";

    /// <summary>
    /// Source: In-Game UI <br/>
    /// Context: 
    /// </summary>
    public const string GROUP_INGAMEUI = "GROUP_INGAMEUI";

    /// <summary>
    /// Source: Show Mod Button <br/>
    /// Context: 
    /// </summary>
    public const string SHOW_MOD_BUTTON = "SHOW_MOD_BUTTON";

    /// <summary>
    /// Source: Mod Button Position <br/>
    /// Context: 
    /// </summary>
    public const string MOD_BUTTON_POSITION = "MOD_BUTTON_POSITION";

    /// <summary>
    /// Source: Panel Position <br/>
    /// Context: 
    /// </summary>
    public const string PANEL_POSITION = "PANEL_POSITION";

    /// <summary>
    /// Source: Please enter the valid values before applying <br/>
    /// Context: 
    /// </summary>
    public const string TIP_DISABLED_APPLYBTN = "TIP_DISABLED_APPLYBTN";
}